version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/client"
    schedule:
      interval: "weekly"

  - package-ecosystem: "elm"
    directory: "/client"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gitsubmodule"
    directory: "/client/elm-material"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/server"
    schedule:
      interval: "weekly"
