# This docker compose file is for building and running a production version of jasb.
# This uses the built images from the github image repository.

version: "3.9"

networks:
  backend:
  frontend:

# You may not want docker to manage your data like this.
# Please see Docker's documentation for more on managing volumes: https://docs.docker.com/compose/compose-file/#volume-configuration-reference
volumes:
  storage-volume:

services:
  server:
    image: "ghcr.io/jads-dev/jasb/server:latest"
    environment:
      NODE_ENV: production
    networks:
      - backend
      - frontend
    depends_on:
      - data
    volumes:
      - /host/path/to/config.json5:/jasb/config.json5:ro
      - /host/path/to/oci-config.cfg:/jasb/oci-config.cfg:ro
      - /host/path/to/oci_api_key.pem:/jasb/oci_api_key.pem:ro
    restart: unless-stopped

  client:
    image: "ghcr.io/jads-dev/jasb/client:latest"
    ports:
      - "80:8080"
    networks:
      - frontend
    depends_on:
      - server
    restart: unless-stopped

  data:
    image: postgres:13
    volumes:
      - storage-volume:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: jasb
      POSTGRES_PASSWORD: CHANGE_ME
      TZ: UTC
    networks:
      - backend
    restart: unless-stopped
