name: Build

on:
  push:
    branches:
      - main
    tags:
      - v*.*.*

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Get build date/time.
        id: date
        run: echo "::set-output name=date::$(date -u --rfc-3339=seconds)"

      - name: Set up QEMU.
        id: qemu
        uses: docker/setup-qemu-action@v1.2.0
        with:
          platforms: arm64

      - name: Setup buildx
        uses: docker/setup-buildx-action@v1

      - name: GHCR login
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/bake-action@v1.4.2
        with:
          files: "docker-bake.hcl"
        env:
          HOST: ghcr.io
          REPO: ${{ github.repository }}
          HASH: ${{ github.sha }}
          BUILD_DATE: ${{ steps.date.outputs.date }}
